baseURL = "https://nnocsupnn.github.io/nnocsupnn.github.io/"
title = "nnocsupnn"
languageCode = "en-us"
theme = "PaperMod"
publishDir = "docs"

[params]
  author = "Nino Manalo Casupanan"
  description = "My developer profile"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true